# Master configuration for the QuantStack (SAFE YAML)

symbols:
  core:
    - EURUSD
    - GBPUSD
    - USDJPY
    - AUDUSD
    - USDCAD
    - USDCHF
    - US500
    - NAS100
    - GER40
    - XAUUSD
    - XAGUSD
    - USOIL
  satellite:
    - EURJPY
    - GBPJPY
    - AUDNZD
    - NZDUSD
    - UK100
    - FRA40
    - JPN225
    - COPPER
    - NATGAS

sleeves:
  tsmom:
    on: true
    lookbacks: [40, 55, 80, 100]
    exit_bars: 80
    vol_target: 0.12
  carry:
    on: true
    top_n: 3
    dxy_vol_halve: true
    vol_target: 0.10
  xsec:
    on: true
    top_q: 0.3
    bot_q: 0.3
    vol_target: 0.10
  mr_vwap:
    on: true
    z: 2.0
    atr_lb: 14
    vol_target: 0.08
  orb_nr7:
    on: true
    or_min: 30
    trail_atr: 1.5
    vol_target: 0.06
  seasonality:
    on: true
    vol_target: 0.06

risk:
  per_trade_risk: 0.005
  inst_risk_cap: 0.08
  corr_guard: 0.6
  mtd_soft: -0.06
  mtd_hard: -0.10

regime:
  features:
    vol_lb: 20
    dispersion_lb_months: 12
  weights:
    Calm:
      tsmom: 0.6
      xsec: 0.6
      mr_vwap: 1.2
      orb_nr7: 0.8
      seasonality: 1.2
      carry: 1.0
    Expansion:
      tsmom: 1.3
      xsec: 1.2
      mr_vwap: 0.5
      orb_nr7: 1.1
      seasonality: 0.7
      carry: 1.0
    RiskOff:
      tsmom: 1.2
      xsec: 0.6
      mr_vwap: 0.3
      orb_nr7: 0.8
      seasonality: 0.6
      carry: 0.5

selection:
  spread_adr_max: 0.005
  adr_floor_ratio: 0.4
  rotate_by: dispersion

execution:
  stop_limit_band: 0.0005
  spread_live_ceiling_mult: 1.5
