# Baseline config for multi-sleeve system

sleeves:
  tsmom:
    lookbacks: [63, 126, 252]
    exit_bars: 10

weights:
  tsmom: 1.0
  xsec: 0.8
  mr: 0.6

risk:
  target_ann_vol: 0.12
  vol_lookback: 20
  max_leverage: 3.0

mtd_gates:
  soft: -0.06
  hard: -0.10

costs:
  csv: data/costs_per_symbol.csv
  fallback_per_leg: 0.0005


# weights:
#   tsmom: 1.0
#   xsec: 0.8
#   mr: 0.6
#   volcarry: 0.4
