universe:
  folder: data/prices_1d
  costs_csv: data/costs_per_symbol.csv
  lookback_years: 5
risk:
  target_ann_vol: 0.15
  vol_lookback: 15
  max_leverage: 2.0
weights:
  tsmom: 1.0
  xsec: 0.8
  mr: 0.6
  volcarry: 0.0
volcarry:
  top_q: 0.25
  bot_q: 0.25
  lookback: 42
mtd_gates:
  soft: -0.06
  hard: -0.1
trade_sanity:
  gap_atr_k: 3.0
  atr_lookback: 14
  vol_spike_mult: 3.0
  vol_spike_window: 60
output:
  positions_csv: signals/positions.csv
  out_prefix_base: DAILY
