name: Meta Allocator Smoke

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run smoke test
        env:
          PYTHONPATH: src
        run: |
          pytest -q tests/alpha_factory/test_meta_allocator_smoke.py -vv --maxfail=1
      - name: Export allocations (demo)
        shell: pwsh
        env:
          PYTHONPATH: src
        run: |
          pwsh -File tools/Export-Allocations.ps1 -Repo .
      - name: Upload allocation CSVs
        uses: actions/upload-artifact@v4
        with:
          name: allocations
          path: artifacts/allocations/*.csv
          if-no-files-found: ignore
