name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true          # pull LFS files (e.g., PDFs, large CSVs)

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt"

      - name: Lint (flake8 optional)
        run: |
          pip install flake8 || echo "flake8 optional"
          flake8 src || echo "Lint warnings ignored for now"

      - name: Smoke test (no MT5)
        run: |
          python -m src.exec.backtest_pnl_demo --folder data/prices_1d --costs_csv data/costs_per_symbol.csv --out_prefix CI_SMOKE --target_ann_vol 0.1 --vol_lookback 30 --max_leverage 2.0 --w_tsmom 1.0 --w_xsec 0.8 --w_mr 0.6 --w_volcarry 0.0 --volcarry_top_q 0.25 --volcarry_bot_q 0.25 --volcarry_lookback 42 --mtd_soft -0.06 --mtd_hard -0.1 --gap_atr_k 3.0 --atr_lookback 14 --vol_spike_mult 3.0 --vol_spike_window 60