name: CI (PS7)

on:
  pull_request:
  workflow_dispatch:

env:
  AF_SKIP_MT5: 1
  PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install (PS7)
        shell: pwsh
        run: pwsh -File tools/CI-Install.ps1

      - name: Checks (Smoke)
        shell: pwsh
        run: pwsh -File tools/CI-Checks.ps1 -SmokeOnly

