name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[dev]"

      - name: Install test deps (dashboards)
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
        run: |
          python -m pip install matplotlib

      - name: Repo Guard (PS7)
        run: pwsh tools/AI-Guard.ps1 -SkipTests

      - name: Ruff (lint)
        run: python -m ruff check .

      - name: Black (format check)
        run: python -m black --check .

      - name: Pytest
        env:
          MPLBACKEND: Agg
          TZ: UTC
        run: python -m pytest -q