name: CI (PS7)

on:
  push:
    branches:
      - main
      - chore/compat-alpha-factory-027
  pull_request:
    branches:
      - main
      - chore/compat-alpha-factory-027

jobs:
  build-test:
    name: Lint & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show PowerShell
        run: |
          $PSVersionTable
          $ErrorActionPreference = 'Stop'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          $ErrorActionPreference = 'Stop'
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }
          pip install ruff black pytest

      - name: Print Python env
        run: |
          python --version
          pip --version
          pip list

      - name: Lint (Ruff)
        run: |
          $ErrorActionPreference = 'Stop'
          python -m ruff check .

      - name: Format check (Black)
        run: |
          $ErrorActionPreference = 'Stop'
          python -m black --check .

      - name: Repo guards
        run: |
          $ErrorActionPreference = 'Stop'
          if (Test-Path tools/AI-Guard.ps1) { pwsh tools/AI-Guard.ps1 }
          if (Test-Path tools/Bootstrap-SelfTest.ps1) { pwsh tools/Bootstrap-SelfTest.ps1 }

      - name: Tests (pytest)
        env:
          TZ: UTC
        run: |
          $ErrorActionPreference = 'Stop'
          python -m pytest -q
