name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run -a

  cli-smoke:
    name: CLI Smoke (CSV + dark HTML)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package (editable)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run CLI smoke (PowerShell 7)
        shell: pwsh
        run: |
          $env:PYTHONPATH = (Resolve-Path ./src).Path
          pwsh -File tools/infra/v1.0/Step-2-CLISmoke.ps1

  docs-smoke:
    name: Docs Smoke (mkdocs build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build docs
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
          mkdocs build --strict
