name: Tests (pytest)

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c .github/constraints-ci.txt
          if ($LASTEXITCODE -ne 0) { Write-Host 'Ignoring constraints install failure'; $global:LASTEXITCODE = 0 }
          pip install pytest pytest-cov -c .github/constraints-ci.txt
        env:
          AF_SKIP_MT5: 1
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
      - name: Run pytest (smoke)
        run: pytest -q --maxfail=1 --disable-warnings tests/ci_smoke_test.py
