name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    runs-on: ubuntu-latest
    strategy:
      matrix: { python-version: ["3.10", "3.11", "3.12"] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: pip-
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: pre-commit run --all-files
      - name: Ensure Matplotlib Agg backend
        shell: pwsh
        run: ./tools/ensure-agg.ps1

      - run: pytest -q --cov=src --cov-report=xml
