name: ci

on:
  push:
    branches: [ main, feat/**, fix/**, docs/**, chore/** ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package (dev extras)
        run: pip install ".[dev]"

      - name: Show environment
        run: |
          python -V
          pip list

      - name: Lint (pre-commit)
        run: pre-commit run -a

      - name: Run tests
        run: pytest -q

      - name: Minimal CLI smoke
        env:
          PYTHONPATH: src
        run: |
          python -m alpha_factory.registry_cli -h
          python -m alpha_factory.registry_cli init --db ci.duckdb
          python -m alpha_factory.registry_cli export --what best --metric sharpe --top 1 --format csv --out best.csv
