name: Daily Report

on:
  workflow_dispatch:
  schedule:
    - cron: "15 17 * * 1-5"  # 17:15 UTC ≈ 18:15 Europe/Warsaw winter; adjust as you like

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install pytest (minimal)
        run: pip install -U pytest

      - name: Run Meta Allocator + Risk Report
        shell: pwsh
        env:
          PYTHONPATH: src
        run: |
          pwsh -File tools/Make-DailyReport.ps1 -OutPath artifacts/reports/latest.md -NoTail

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: |
            artifacts/reports/latest.md
            artifacts/allocations/*.csv
          if-no-files-found: ignore
