name: Docs Smoke (standalone)
on:
  workflow_dispatch:
  push:
    branches: [ci/docs-fix]

jobs:
  docs:
    name: mkdocs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Build docs
        run: mkdocs build --strict
