name: Lint (Ruff + Black)
on:
  pull_request:
  workflow_dispatch:
env:
  AF_SKIP_MT5: '1'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Ruff (check)
        run: ruff check .
      - name: Black (check)
        run: black --check .
