name: Manual Export
on:
  workflow_dispatch:
    inputs:
      pairs:
        description: "Comma-separated pairs (e.g. EURUSD,GBPUSD,USDJPY)"
        default: "EURUSD,GBPUSD,USDJPY"
      tf:
        description: "Timeframe"
        default: "H1"
      start:
        description: "Start date (YYYY-MM-DD)"
        default: "2024-01-01"
      end:
        description: "End date (YYYY-MM-DD)"
        default: "2024-01-10"
      upload_to_s3:
        description: "Upload exports to S3?"
        type: boolean
        default: false

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: '${{ github.workspace }}:${{ github.workspace }}/src'
      PAIRS: '${{ inputs.pairs }}'
      TF: '${{ inputs.tf }}'
      START: '${{ inputs.start }}'
      END: '${{ inputs.end }}'
      UPLOAD_TO_S3: '${{ inputs.upload_to_s3 }}'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Run exporter (best-effort)
        run: |
          python -m src.infra.export_features || echo "exporter finished (or skipped)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: feature-exports-${{ github.run_id }}
          path: artifacts/**
          if-no-files-found: warn
