name: Meta Allocator Nightly

on:
  workflow_dispatch: {}
  schedule:
    - cron: "10 2 * * *"   # 02:10 UTC daily

permissions:
  contents: read

env:
  AF_SKIP_MT5: "1"
  PYTHONPATH: ${{ github.workspace }}/src

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ensure metrics & outdir
        shell: bash
        run: |
          set -e
          mkdir -p configs artifacts/allocations
          if [ ! -f configs/meta_metrics.json ]; then
            printf '{"TF":{"sharpe":1.2,"dd":0.06},"MR":{"sharpe":1.0,"dd":0.05},"VOL":{"sharpe":0.8,"dd":0.04}}' > configs/meta_metrics.json
          fi

      - name: Run meta allocator (timestamped + latest)
        shell: bash
        run: |
          set -e
          python -m alpha_factory.cli_meta_alloc --mode ewma --metrics configs/meta_metrics.json --outdir artifacts/allocations --write-latest
          ls -l artifacts/allocations

      - name: Upload nightly CSVs
        uses: actions/upload-artifact@v4
        with:
          name: nightly-allocations
          path: artifacts/allocations/*_alloc.csv
