name: Nightly

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run exporter (best-effort)
        env:
          PYTHONPATH: '${{ github.workspace }}:${{ github.workspace }}/src'
        run: |
          python -m src.infra.export_features || echo "exporter finished (or skipped)"

      - name: Upload artifacts (anything under artifacts/)
        uses: actions/upload-artifact@v4
        with:
          name: nightly-${{ github.run_id }}
          path: artifacts/**
          if-no-files-found: warn
