env:
  AF_SKIP_MT5: '1'
name: Check for push or pull_request_target triggers
on:
  pull_request:
      paths:
        - alpha_factory/**
        - tests/**
        - tools/**
        - configs/**
        - mt5/**
  workflow_dispatch:

jobs:
  check-forbidden-triggers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if forbidden triggers exist
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(.github/workflows/*.yml .github/workflows/*.yaml)
          banned=('^\s*push\s*:' '^\s*pull_request_target\s*:')
          bad=0
          for f in "${files[@]}"; do
            for pat in "${banned[@]}"; do
              if grep -P -n "$pat" "$f" >/dev/null 2>&1; then
                echo "::error file=$f::Forbidden trigger matched pattern: $pat"
                bad=1
              fi
            done
          done
          exit $bad

