# temporarily disabled (replaced by tests.yml + lint.yml)
# 2025-10-15T21:21:20Z
name: pr-ci (disabled)
on:
  workflow_call:
jobs:
  noop:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo 'disabled'

