name: PR CI

on:
  pull_request:
    branches: ['**']

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONDONTWRITEBYTECODE: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      - name: Lint (pre-commit)
        run: pre-commit run -a

      - name: Tests
        run: pytest -q
