name: Tests (pytest)
on:
  pull_request:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AF_SKIP_MT5: ''1''
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov
      - name: Export PYTHONPATH
        shell: bash
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/src" >> "$GITHUB_ENV"      - name: Run pytest
        run: pytest -q --maxfail=1 --disable-warnings tests/ci_smoke_test.py
