env:
  AF_SKIP_MT5: '1'
name: Tests (pytest)

on:
  pull_request:
      paths:
        - alpha_factory/**
        - tests/**
        - tools/**
        - configs/**
        - mt5/**
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c .github/constraints-ci.txt || true
          pip install pytest pytest-cov -c .github/constraints-ci.txt

      - name: Run pytest
        run: pytest -q --maxfail=1 --disable-warnings

