name: Tests (pytest)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
  - name: Export PYTHONPATH
    shell: bash
    run: |
      echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c .github/constraints-ci.txt || true
          pip install pytest pytest-cov -c .github/constraints-ci.txt
  - name: Set PYTHONPATH (repo root first)
    shell: bash
    run: |
      echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

        run: pytest -q --maxfail=1 --disable-warnings tests/ci_smoke_test.py







