name: Tests (pytest)
on:
  pull_request:
  workflow_dispatch:
env:
  AF_SKIP_MT5: '1'  # disable MetaTrader5 in CI
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Install project + test deps (fall back to direct)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -q pandas numpy pyarrow duckdb pytest
      - name: Pytest (CI mode)
        env:
          AF_SKIP_MT5: '1'
        run: |
          pytest -q --disable-warnings
