name: Tests (pytest)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      AF_SKIP_MT5: '1'
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pandas pyarrow numpy
      - name: Run pytest (smoke only)
        run: |
          pytest -q -k "ci_smoke_test" --disable-warnings
